// web/src/proofPort.ts
// The seam: the single place web/ selects which @creva-zk/api proof-port
// implementation backs a screen, plus the adapter turning a port's
// ApiResult into the ProofState the screens already render. The source is
// chosen at build time by VITE_PORT_SOURCE, so switching between the stub
// and a real proof needs no code edit — see the note below.

import type { ApiResult, BackingProofPort, IdentityProofPort } from '@creva-zk/api';
import {
  createBridgeBackingPort,
  createBridgeIdentityPort,
  createRealBackingPort,
  createRealIdentityPort,
  createStubBackingPort,
  createStubIdentityPort,
} from '@creva-zk/api';
import type { LaceOptions } from '@creva-zk/api/lace';
import { createLazyLaceBackingPort, createLazyLaceIdentityPort } from './lacePort';
import type { ProofState } from './domain/proofState';
import { settleDegraded, settleFailed, settleReady } from './domain/proofState';

export type PortSource = 'stub' | 'real' | 'bridge' | 'lace';

// 'stub' by default so a clone, a test run and every screen render stay
// instant. Three opt-ins drive the screens from an actual proof instead:
//
//   VITE_PORT_SOURCE=real   the in-process port — Node only, so this is for
//                           a Node caller, not for the browser.
//   VITE_PORT_SOURCE=bridge the browser-safe port: it fetches the local
//                           proof server in api/ (`npm run serve --workspace
//                           api`), which owns the Node-only call path and
//                           the exclusive private-state lock.
//   VITE_PORT_SOURCE=lace   the browser-direct path, and the one the product
//                           ships: no Node process of ours in the middle at
//                           all. Lace is the wallet, the indexer and node
//                           come from Lace's own settings, and the proof is
//                           generated by the local proof server the user
//                           configured there.
//
//   VITE_PORT_SOURCE=bridge npm run dev --workspace web
//
// Either way a call costs ~23.7s against the local network, which is why
// they are opt-in rather than the default. Anything unrecognised falls back
// to the stub, so a typo degrades to the safe side instead of silently
// blocking every screen for half a minute.
export function resolvePortSource(raw: string | undefined): PortSource {
  if (raw === 'real') return 'real';
  if (raw === 'bridge') return 'bridge';
  if (raw === 'lace') return 'lace';
  return 'stub';
}

const PORT_SOURCE: PortSource = resolvePortSource(import.meta.env?.VITE_PORT_SOURCE);

export function activePortSource(): PortSource {
  return PORT_SOURCE;
}

// Where the bridge port looks for that server. Left undefined unless the
// build sets it, so @creva-zk/api's own default (http://localhost:8787)
// applies.
const BRIDGE_OPTIONS = { baseUrl: import.meta.env?.VITE_BRIDGE_URL } as const;

// The browser-direct path needs no server of ours at all, so the only things
// a build can say are which network to insist on and where the compiled
// circuit's ZK artifacts are served from. Both stay unset unless the build
// sets them, so @creva-zk/api's own defaults apply. The port itself loads
// lazily — see lacePort.ts — so no other build carries the ledger's WASM.
const LACE_OPTIONS: LaceOptions = {
  ...(import.meta.env?.VITE_LACE_NETWORK_ID === undefined
    ? {}
    : { expectedNetworkId: import.meta.env.VITE_LACE_NETWORK_ID }),
  ...(import.meta.env?.VITE_ZK_CONFIG_URL === undefined
    ? {}
    : { zkConfigBaseUrl: import.meta.env.VITE_ZK_CONFIG_URL }),
};

export function selectBackingPort(): BackingProofPort {
  switch (PORT_SOURCE) {
    case 'real':
      return createRealBackingPort();
    case 'bridge':
      return createBridgeBackingPort(BRIDGE_OPTIONS);
    case 'lace':
      return createLazyLaceBackingPort(LACE_OPTIONS);
    default:
      return createStubBackingPort();
  }
}

export function selectIdentityPort(): IdentityProofPort {
  switch (PORT_SOURCE) {
    case 'real':
      return createRealIdentityPort();
    case 'bridge':
      return createBridgeIdentityPort(BRIDGE_OPTIONS);
    case 'lace':
      return createLazyLaceIdentityPort(LACE_OPTIONS);
    default:
      return createStubIdentityPort();
  }
}

// The two non-ok outcomes are different answers to the user and must not be
// collapsed:
//
//   failed   the predicate does not hold — the collateral falls short, the
//            attestation does not match. A real answer, and it is "no".
//   degraded nobody could check. The proof server is down, the call timed
//            out, the body was not an ApiResult. Not an answer at all.
//
// Rendering degraded as failed would tell her she does not qualify when in
// fact nothing was evaluated, so the reason travels through to the screen.
//
// A predicate that does not hold is an `ok` result carrying a negative
// outcome — tier "none", verified false — not a degraded one. `holds` is how
// the caller names that, since this adapter is generic over the outcome and
// cannot read it. Omitted, every ok result is treated as holding.
export function toProofState<T>(result: ApiResult<T>, holds: (value: T) => boolean = () => true): ProofState<T> {
  if (result.status === 'degraded') return settleDegraded<T>(result.degraded.reason);
  return holds(result.value) ? settleReady(result.value) : settleFailed<T>();
}
