// web/src/proofPort.ts
// The seam: the single place web/ selects which @creva-zk/api proof-port
// implementation backs a screen, plus the adapter turning a port's
// ApiResult into the ProofState the screens already render. The source is
// chosen at build time by VITE_PORT_SOURCE, so switching between the stub
// and a real proof needs no code edit — see the note below.

import type { ApiResult, BackingProofPort, IdentityProofPort, JubjubPoint } from '@creva-zk/api';
import {
  createBridgeBackingPort,
  createBridgeIdentityPort,
  createStubBackingPort,
  createStubIdentityPort,
} from '@creva-zk/api';
// Not from '@creva-zk/api': the real port runs the circuit in-process and
// reaches Docker and node:, so it is not in that entry at all. A browser
// asking for it gets the honest stand-in.
import { createRealBackingPort, createRealIdentityPort } from './realUnavailable';
import type { LaceOptions } from '@creva-zk/api/lace';
import { createLazyLaceBackingPort, createLazyLaceIdentityPort } from './lacePort';
import { SYNTHETIC_ISSUER_KEY } from './domain/demoInputs';
import type { ProofState } from './domain/proofState';
import { settleDegraded, settleFailed, settleReady } from './domain/proofState';

export type PortSource = 'stub' | 'real' | 'bridge' | 'lace';

// 'stub' by default so a clone, a test run and every screen render stay
// instant. Three opt-ins drive the screens from an actual proof instead:
//
//   VITE_PORT_SOURCE=real   the in-process port — it starts the local
//                           network, deploys once and calls the circuit, so
//                           it is for a Node caller (api/'s own serve and
//                           demo). In a browser it degrades, by design.
//   VITE_PORT_SOURCE=bridge the browser-safe port: it fetches the local
//                           proof server in api/ (`npm run serve --workspace
//                           api`), which owns the Node-only call path and
//                           the exclusive private-state lock.
//   VITE_PORT_SOURCE=lace   the browser-direct path, and the one the product
//                           ships: no Node process of ours in the middle at
//                           all. Lace is the wallet, the indexer and node
//                           come from Lace's own settings, and the proof is
//                           generated by the local proof server the user
//                           configured there.
//
//   VITE_PORT_SOURCE=bridge npm run dev --workspace web
//
// Either way a call costs ~23.7s against the local network, which is why
// they are opt-in rather than the default. Anything unrecognised falls back
// to the stub, so a typo degrades to the safe side instead of silently
// blocking every screen for half a minute.
export function resolvePortSource(raw: string | undefined): PortSource {
  if (raw === 'real') return 'real';
  if (raw === 'bridge') return 'bridge';
  if (raw === 'lace') return 'lace';
  return 'stub';
}

const PORT_SOURCE: PortSource = resolvePortSource(import.meta.env?.VITE_PORT_SOURCE);

export function activePortSource(): PortSource {
  return PORT_SOURCE;
}

// Where the bridge port looks for that server. Left undefined unless the
// build sets it, so @creva-zk/api's own default (http://localhost:8787)
// applies.
const BRIDGE_OPTIONS = { baseUrl: import.meta.env?.VITE_BRIDGE_URL } as const;

// The browser-direct path needs no server of ours at all. What a build must
// say is where the backing contract lives: this path JOINS a contract
// deployed once from the CLI instead of deploying one in the page, which
// costs her ~19s and a signature on a deployment that is not hers. Without
// the address the port degrades `contract_not_found` — it never falls back
// to deploying. Network id and artifact base URL stay unset unless the build
// sets them, so @creva-zk/api's own defaults apply. The port itself loads
// lazily — see lacePort.ts — so no other build carries the ledger's WASM.
const LACE_OPTIONS: LaceOptions = {
  ...(import.meta.env?.VITE_BACKING_CONTRACT_ADDRESS === undefined
    ? {}
    : { contractAddress: import.meta.env.VITE_BACKING_CONTRACT_ADDRESS }),
  ...(import.meta.env?.VITE_LACE_NETWORK_ID === undefined
    ? {}
    : { expectedNetworkId: import.meta.env.VITE_LACE_NETWORK_ID }),
  ...(import.meta.env?.VITE_ZK_CONFIG_URL === undefined
    ? {}
    : { zkConfigBaseUrl: import.meta.env.VITE_ZK_CONFIG_URL }),
  // The one place this app prints anything. The network id a given Lace
  // build reports is not something this repository can know, and a reviewer
  // staring at "Red equivocada" needs to read the string the wallet actually
  // sent — so it, and every raw provider error behind a degraded reason, go
  // to the console. Nothing user-facing is decided by it.
  logger: {
    info: (obj, msg) => console.info(`[creva-zk] ${msg}`, obj),
    error: (obj, msg) => console.error(`[creva-zk] ${msg}`, obj),
  },
};

export function selectBackingPort(): BackingProofPort {
  switch (PORT_SOURCE) {
    case 'real':
      return createRealBackingPort();
    case 'bridge':
      return createBridgeBackingPort(BRIDGE_OPTIONS);
    case 'lace':
      return createLazyLaceBackingPort(LACE_OPTIONS);
    default:
      return createStubBackingPort();
  }
}

// Which issuer key an identity proof is checked against, per source.
//
// On the bridge path the browser names none. The server publishes the key
// its own deployment signs under and the port fetches it before proving —
// naming one here is what made the circuit abort, because a key this app
// invented is not the key the attestation was signed with. The zero point
// goes over as a marker that no browser-side key applies; the bridge port
// replaces it and never sends it.
//
// Every other source proves against the synthetic issuer this demo ships,
// which is the key its own synthetic attestation was signed under.
const NO_BROWSER_ISSUER_KEY: JubjubPoint = { x: 0n, y: 0n };

export function identityIssuerKey(): JubjubPoint {
  return PORT_SOURCE === 'bridge' ? NO_BROWSER_ISSUER_KEY : SYNTHETIC_ISSUER_KEY;
}

export function selectIdentityPort(): IdentityProofPort {
  switch (PORT_SOURCE) {
    case 'real':
      return createRealIdentityPort();
    case 'bridge':
      return createBridgeIdentityPort(BRIDGE_OPTIONS);
    case 'lace':
      return createLazyLaceIdentityPort(LACE_OPTIONS);
    default:
      return createStubIdentityPort();
  }
}

// The two non-ok outcomes are different answers to the user and must not be
// collapsed:
//
//   failed   the predicate does not hold — the collateral falls short, the
//            attestation does not match. A real answer, and it is "no".
//   degraded nobody could check. The proof server is down, the call timed
//            out, the body was not an ApiResult. Not an answer at all.
//
// Rendering degraded as failed would tell her she does not qualify when in
// fact nothing was evaluated, so the reason travels through to the screen.
//
// A predicate that does not hold is an `ok` result carrying a negative
// outcome — tier "none", verified false — not a degraded one. `holds` is how
// the caller names that, since this adapter is generic over the outcome and
// cannot read it. Omitted, every ok result is treated as holding.
export function toProofState<T>(result: ApiResult<T>, holds: (value: T) => boolean = () => true): ProofState<T> {
  if (result.status === 'degraded') return settleDegraded<T>(result.degraded.reason);
  return holds(result.value) ? settleReady(result.value) : settleFailed<T>();
}
